server: 
  port: 8762
  
#/{application}/{profile}[/{label}]
#/{application}-{profile}.yml
#/{label}/{application}-{profile}.yml
#/{application}-{profile}.properties
#/{label}/{application}-{profile}.properties
spring: 
  application:
    name: configcenter
  cloud: 
    config: 
      server: 
        git: 
          uri: https://github.com/qintianjie/cloud-sample-v2
          searchPaths: config-repo/base