server: 
  port: 8090
  
spring: 
  application: 
    name: cloud-sample-consumer
  cloud: 
    config:  
      uri: http://localhost:8762
    
eureka:
  instance: 
    instanceId:  ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
      
provider: 
  name: cloud-sample-provider

# ribbon 请求 provider 对应的  spring.applicaiton.name ，供  LoadBalancer 时从 Eureka 查对应的服务用
colorcc-sample-consumer-ribbon: 
  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:8081,localhost:8082
    ServerListRefreshInterval: 1000
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true